exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('garments')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('garments').insert(DEMO_GARMENTS);
    });
};

const DEMO_GARMENTS = [
  {
    name: 'Advance arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Microfiber with grip-top',
    brand: 'Sigvaris',
    size_label: 'x-small',
    lengths: 'normal, long',
    f_min: 24,
    f_max: 32,
    c_min: 13,
    c_max: 14,
    a_min: 16,
    a_max: 20,
  },
  {
    name: 'Advance arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Microfiber with grip-top',
    brand: 'Sigvaris',
    size_label: 'x-small PLUS',
    lengths: 'normal, long',
    f_min: 32,
    f_max: 38,
    c_min: 13,
    c_max: 14,
    a_min: 16,
    a_max: 20,
  },
  {
    name: 'Advance arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Microfiber with grip-top',
    brand: 'Sigvaris',
    size_label: 'small',
    lengths: 'normal, long',
    f_min: 26,
    f_max: 34,
    c_min: 14,
    c_max: 16,
    a_min: 17,
    a_max: 21,
  },
  {
    name: 'Advance arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Microfiber with grip-top',
    brand: 'Sigvaris',
    size_label: 'small PLUS',
    lengths: 'normal, long',
    f_min: 34,
    f_max: 40,
    c_min: 14,
    c_max: 16,
    a_min: 17,
    a_max: 21,
  },
  {
    name: 'Advance arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Microfiber with grip-top',
    brand: 'Sigvaris',
    size_label: 'medium',
    lengths: 'normal, long',
    f_min: 29,
    f_max: 37,
    c_min: 16,
    c_max: 18,
    a_min: 18,
    a_max: 22,
  },
  {
    name: 'Advance arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Microfiber with grip-top',
    brand: 'Sigvaris',
    size_label: 'medium PLUS',
    lengths: 'normal, long',
    f_min: 37,
    f_max: 43,
    c_min: 16,
    c_max: 18,
    a_min: 18,
    a_max: 22,
  },
  {
    name: 'Advance arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Microfiber with grip-top',
    brand: 'Sigvaris',
    size_label: 'large',
    lengths: 'normal, long',
    f_min: 32,
    f_max: 40,
    c_min: 18,
    c_max: 20,
    a_min: 19,
    a_max: 23,
  },
  {
    name: 'Advance arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Microfiber with grip-top',
    brand: 'Sigvaris',
    size_label: 'large PLUS',
    lengths: 'normal, long',
    f_min: 40,
    f_max: 46,
    c_min: 18,
    c_max: 20,
    a_min: 19,
    a_max: 23,
  },
  {
    name: 'Advance arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Microfiber with grip-top',
    brand: 'Sigvaris',
    size_label: 'x-large',
    lengths: 'normal, long',
    f_min: 34,
    f_max: 42,
    c_min: 20,
    c_max: 23,
    a_min: 20,
    a_max: 24,
  },
  {
    name: 'Advance arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Microfiber with grip-top',
    brand: 'Sigvaris',
    size_label: 'x-large PLUS',
    lengths: 'normal, long',
    f_min: 42,
    f_max: 48,
    c_min: 20,
    c_max: 23,
    a_min: 20,
    a_max: 24,
  },
  {
    name: 'Traditional 503 arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Woven natural rubber threads, with grip-top',
    brand: 'Sigvaris',
    size_label: 'small',
    lengths: 'short, long',
    f_min: 24,
    f_max: 30,
    d_min: 20,
    d_max: 24,
    c_min: 13,
    c_max: 16,
    a_min: 16,
    a_max: 19,
  },
  {
    name: 'Traditional 503 arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Woven natural rubber threads, with grip-top',
    brand: 'Sigvaris',
    size_label: 'medium',
    lengths: 'short, long',
    f_min: 30,
    f_max: 36,
    d_min: 24,
    d_max: 28,
    c_min: 16,
    c_max: 19,
    a_min: 19,
    a_max: 22,
  },
  {
    name: 'Traditional 503 arm (A-G with mitten) Class 2 (Grip-top)',
    limb: 'arm',
    type: 'sleeve with gauntlet',
    compression_level: 'class 2',
    construction: 'Woven natural rubber threads, with grip-top',
    brand: 'Sigvaris',
    size_label: 'large',
    lengths: 'short, long',
    f_min: 36,
    f_max: 42,
    d_min: 28,
    d_max: 32,
    c_min: 19,
    c_max: 22,
    a_min: 22,
    a_max: 25,
  },
];
